### ISSUE TITLE
dnstap receiver stop to work

### ISSUE THREAD

**Issue by anetrjuns** [dmachard/dnstap-receiver#26]
Hi,

I'm installed dnstap-receiver with dnsdist. I have 20k logs/sec and dnstap receiver stop to work after below log 
```
Mar 07 21:59:06 dnsdist01 systemd[1]: Started Dnstap Receiver.
Mar 07 21:59:06 dnsdist01 dnstap_receiver[3687]: 2021-03-07 21:59:06,690 DEBUG External config file loaded
Mar 07 21:59:06 dnsdist01 dnstap_receiver[3687]: 2021-03-07 21:59:06,691 DEBUG Start receiver...
Mar 07 21:59:06 dnsdist01 dnstap_receiver[3687]: 2021-03-07 21:59:06,691 DEBUG Output handler: file
Mar 07 21:59:06 dnsdist01 dnstap_receiver[3687]: 2021-03-07 21:59:06,691 DEBUG Input handler: unix socket
Mar 07 21:59:06 dnsdist01 dnstap_receiver[3687]: 2021-03-07 21:59:06,691 DEBUG Input handler: listening on /var/run/dnsdist/dnstap.sock
Mar 07 21:59:06 dnsdist01 dnstap_receiver[3687]: 2021-03-07 21:59:06,693 DEBUG Webserver: listening on 0.0.0.0:8080
Mar 07 21:59:10 dnsdist01 dnstap_receiver[3687]: 2021-03-07 21:59:10,446 DEBUG Input handler: new connection from (unix-socket)
Mar 07 21:59:10 dnsdist01 dnstap_receiver[3687]: 2021-03-07 21:59:10,447 DEBUG Input handler: control ready received from (unix-socket)
Mar 07 21:59:10 dnsdist01 dnstap_receiver[3687]: 2021-03-07 21:59:10,447 DEBUG Input handler: sending control accept to (unix-socket)
Mar 07 21:59:10 dnsdist01 dnstap_receiver[3687]: 2021-03-07 21:59:10,449 DEBUG Input handler: control start received from (unix-socket)
Mar 07 21:59:44 dnsdist01 dnstap_receiver[3687]: 2021-03-07 21:59:44,499 DEBUG Input handler: (unix-socket) - closed
Mar 07 21:59:44 dnsdist01 dnstap_receiver[3687]: Task exception was never retrieved
Mar 07 21:59:44 dnsdist01 dnstap_receiver[3687]: future: <Task finished coro=<cb_onconnect() done, defined at /usr/local/lib/python3.6/site-packages/dnstap_receiver/inputs/input_socket.py:13> exception=UnicodeDecodeError('utf-8', b'150.109.179.161m\xb7\xc9@\x7f+\x01\xe9\xac\xba\x9e\xf4\xd3\xe9l.', 16, 17, 'invalid start byte')>
Mar 07 21:59:44 dnsdist01 dnstap_receiver[3687]: Traceback (most recent call last):
Mar 07 21:59:44 dnsdist01 dnstap_receiver[3687]: File "/usr/local/lib/python3.6/site-packages/dnstap_receiver/inputs/input_socket.py", line 67, in cb_onconnect
Mar 07 21:59:44 dnsdist01 dnstap_receiver[3687]: await dnstap_decoder.cb_ondnstap(dnstap_protobuf, payload, cfg, queues_list, stats, geoip_reader, cache)
Mar 07 21:59:44 dnsdist01 dnstap_receiver[3687]: File "/usr/local/lib/python3.6/site-packages/dnstap_receiver/inputs/dnstap_decoder.py", line 124, in cb_ondnstap
Mar 07 21:59:44 dnsdist01 dnstap_receiver[3687]: tap["qname"] = qname.decode()
Mar 07 21:59:44 dnsdist01 dnstap_receiver[3687]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 16: invalid start byte
```

**Comment by dmachard** [comment]
Hi, 
I applied a fix (workaround) , perhaps it's sufficient
Could you test on your side ?
Denis

**Comment by anetrjuns** [comment]
Yes, it's work 

Thanks
