### ISSUE TITLE
Looks like subprocess crashed after  some dns requests

### ISSUE THREAD

**Issue by KVInventoR** [dmachard/dnstap-receiver#27]
Hi there,

I faced that our dnstap-receiver configuration from latest version of docker image after a couple of minutes just stopped receiving  any traffic.
In logs I found next records:

```
future: <Task finished name='Task-10' coro=<cb_onconnect() done, defined at /home/dnstap/dnstap_receiver/inputs/input_socket.py:13> exception=UnicodeDecodeError('utf-8', b'178.2.1.64\xa0.fre.com.', 13, 14, 'invalid start byte')>
Traceback (most recent call last):
  File "/home/dnstap/dnstap_receiver/inputs/input_socket.py", line 67, in cb_onconnect
    await dnstap_decoder.cb_ondnstap(dnstap_protobuf, payload, cfg, queues_list, stats, geoip_reader, cache)
  File "/home/dnstap/dnstap_receiver/inputs/dnstap_decoder.py", line 124, in cb_ondnstap
    tap["qname"] = qname.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 13: invalid start byte

```

Also, we receive a lot of strange dns requests which looks like:
```
'GET\032/\032HTTP/1.1\013\010Host.enzym.com.ua'
'_minecraft._tcp.play.mcastra.ru\010.free.ua'
(null).corp.sport.ua
Automatically\032added\032for\032iOS\032&\032OS\032X\032Mail.corp.sport.ua
https://ynuf.aliapp.org/saveWb.json?.corp.sport.ua
```

**Comment by dmachard** [comment]
hi,

Can you update with the release 4.2.1  ?

your line 124 should be like below

`tap["qname"] = qname.decode(errors="ignore")`

denis

**Comment by dmachard** [comment]
duplicate issue with #26

**Comment by KVInventoR** [comment]
Hi @dmachard 
yes, it works well
thank you
