### ISSUE TITLE
missing codecs in 2.1.0

### ISSUE THREAD

**Issue by Kralian** [dmachard/dnstap-receiver#9]
pip install dnstap-receiver==2.1.0 results in

Traceback (most recent call last):
  File "~/.virtualenvs/dnstap/bin/dnstap_receiver", line 5, in <module>
    from dnstap_receiver.receiver import start_receiver
  File "~/.virtualenvs/dnstap/lib/python3.7/site-packages/dnstap_receiver/__init__.py", line 3, in <module>
    from dnstap_receiver.receiver import start_receiver
  File "~/.virtualenvs/dnstap/lib/python3.7/site-packages/dnstap_receiver/receiver.py", line 23, in <module>    from dnstap_receiver.codec import dnstap_pb2
ModuleNotFoundError: No module named 'dnstap_receiver.codec'

It works with ==2.0.2

**Comment by dmachard** [comment]
Thanks for reporting this! regression fixed in 2.1.1
